name: learn-github-actions

on:
  release:
    types: [ created ]

jobs:
  show_release_tag:
    runs-on: ubuntu-latest
    steps:
      - name: print release info
        run: |
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.sha }}"
          echo "${{ github.ref }}"

      - name: checkout
        uses: actions/checkout@v2

      - name: checkout with tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: checkout with ref
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: checkout with sha
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
